export type NodeDoc = {
  id: string;
  name: string;
  nodeLabel: string;
  module: string;
  tCode?: string;
  route?: string;
  purpose: string;
  requiredFields: string[];
  optionalFields: string[];
  relations: string[];
  apis: string[];
  notes: string[];
};

export const nodeDocs: NodeDoc[] = [
  {
    id: "project",
    name: "Project",
    nodeLabel: "Project",
    module: "project",
    purpose: "Quản lý workspace và ánh xạ sang Neo4j database qua dbName.",
    requiredFields: ["name", "dbName"],
    optionalFields: ["id", "description", "status", "notes", "tags"],
    relations: ["Node quản trị, không tham gia lore graph chính"],
    apis: ["GET /projects", "POST /projects"],
    notes: ["status mặc định active", "Có createdAt/updatedAt"],
  },
  {
    id: "overview",
    name: "Overview",
    nodeLabel: "Overview",
    module: "overview",
    tCode: "OV01",
    route: "/overview",
    purpose: "Tổng quan cốt lõi của truyện/project.",
    requiredFields: ["title"],
    optionalFields: [
      "subtitle",
      "genre[]",
      "shortSummary",
      "worldOverview",
      "technologyEra",
    ],
    relations: ["Thường 1 bản ghi overview cho 1 database"],
    apis: ["GET /overview", "POST /overview", "PUT /overview"],
    notes: ["Dùng cho dashboard mở đầu"],
  },
  {
    id: "character",
    name: "Character",
    nodeLabel: "Character",
    module: "character",
    tCode: "CH01",
    route: "/characters",
    purpose: "Node trung tâm narrative: nhân vật, vai trò, trạng thái, tâm lý.",
    requiredFields: ["name", "gender"],
    optionalFields: [
      "alias[]",
      "level",
      "status",
      "importance",
      "age",
      "race",
      "specialAbilities[]",
      "appearance",
      "personalityTraits[]",
      "beliefs[]",
      "fears[]",
      "desires[]",
      "weaknesses[]",
      "origin",
      "background",
      "currentLocation",
      "currentGoal",
      "notes",
      "tags[]",
      "extra",
    ],
    relations: [
      "CHARACTER_HAS_RACE -> Race",
      "CHARACTER_HAS_RANK -> Rank",
      "CHARACTER_HAS_SPECIAL_ABILITY -> SpecialAbility",
      "CHARACTER_RELATES_TO -> Character",
      "PARTICIPATES_IN -> Event",
      "OWNS_ITEM -> Item",
      "SCENE_FEATURES_CHARACTER <- Scene",
    ],
    apis: [
      "GET /characters",
      "POST /characters",
      "PUT /characters/:id",
      "DELETE /characters/:id",
    ],
    notes: [
      "Hỗ trợ filter/pagination/search q ở BE",
      "Giữ tương thích ngược với isMainCharacter (legacy)",
    ],
  },
  {
    id: "race",
    name: "Race",
    nodeLabel: "Race",
    module: "race",
    tCode: "RA01",
    route: "/races",
    purpose: "Master data chủng tộc cho character.",
    requiredFields: ["name"],
    optionalFields: [
      "alias[]",
      "description",
      "origin",
      "traits[]",
      "culture",
      "lifespan",
      "notes",
      "tags[]",
    ],
    relations: ["CHARACTER_HAS_RACE <- Character"],
    apis: ["GET /races", "POST /races", "PUT /races/:id", "DELETE /races/:id"],
    notes: ["Dùng làm lookup trong form Character"],
  },
  {
    id: "rank-system",
    name: "Rank System",
    nodeLabel: "RankSystem",
    module: "rank-system",
    tCode: "RS01",
    route: "/rank-systems",
    purpose: "Khung hệ thống rank, chứa nhiều node Rank.",
    requiredFields: ["name"],
    optionalFields: [
      "code",
      "description",
      "domain",
      "energyTypeId",
      "energyTypeName",
      "priority",
      "isPrimary",
      "tags[]",
    ],
    relations: ["HAS_RANK -> Rank"],
    apis: [
      "GET /rank-systems",
      "POST /rank-systems",
      "PUT /rank-systems/:id",
      "DELETE /rank-systems/:id",
      "GET /rank-systems/:id/ranks",
    ],
    notes: [
      "code là mã ngắn của cả hệ, không phải rankId",
      "domain dùng để nhóm ngữ nghĩa hệ",
    ],
  },
  {
    id: "energy-type",
    name: "Energy Type",
    nodeLabel: "EnergyType",
    module: "energy-type",
    tCode: "EN01",
    route: "/energy-types",
    purpose: "Master data loại năng lượng dùng bởi các hệ thống cấp bậc.",
    requiredFields: ["code", "name"],
    optionalFields: ["description", "color", "isActive"],
    relations: ["USES_ENERGY <- RankSystem"],
    apis: [
      "GET /energy-types",
      "POST /energy-types",
      "PUT /energy-types/:id",
      "DELETE /energy-types/:id",
    ],
    notes: [
      "Dùng để chuẩn hóa nguồn năng lượng thay vì nhập text tự do",
      "Có thể bật/tắt hoạt động để ẩn khỏi lựa chọn",
    ],
  },
  {
    id: "rank",
    name: "Rank",
    nodeLabel: "Rank",
    module: "rank",
    tCode: "RK01",
    route: "/ranks",
    purpose: "Node cấp bậc trong một RankSystem.",
    requiredFields: ["name"],
    optionalFields: [
      "systemId",
      "alias[]",
      "tier",
      "system",
      "description",
      "notes",
      "tags[]",
      "color",
    ],
    relations: [
      "HAS_RANK <- RankSystem",
      "RANK_NEXT -> Rank",
      "CHARACTER_HAS_RANK <- Character",
    ],
    apis: [
      "GET /ranks",
      "POST /ranks",
      "PUT /ranks/:id",
      "DELETE /ranks/:id",
      "POST /ranks/link",
      "POST /ranks/unlink",
      "POST /ranks/link/conditions",
    ],
    notes: [
      "RANK_NEXT có metadata điều kiện thăng cấp",
      "tier hiện là string để map vào cột sức mạnh",
      "Board rank hỗ trợ nhiều nhánh thăng cấp (1 -> N và N -> 1)",
      "FE hiện cho phép nối rank khác hệ thống",
      "Layout board rank được lưu DB theo project",
    ],
  },
  {
    id: "map-system",
    name: "Map System",
    nodeLabel: "MapSystem",
    module: "map-system",
    tCode: "MP01",
    route: "/map-systems",
    purpose: "Lưu cấu hình sinh bản đồ theo seed (MVP generator).",
    requiredFields: ["name"],
    optionalFields: [
      "code",
      "description",
      "scope",
      "seed",
      "width",
      "height",
      "seaLevel",
      "climatePreset",
      "config",
      "notes",
      "tags[]",
    ],
    relations: [
      "MVP hiện tại chưa bắt buộc quan hệ graph",
      "Giai đoạn sau có thể nối MAP_HAS_LOCATION -> Location",
    ],
    apis: [
      "GET /map-systems",
      "POST /map-systems",
      "PUT /map-systems/:id",
      "DELETE /map-systems/:id",
    ],
    notes: [
      "config lưu JSON string của tham số generator",
      "seed + size + seaLevel dùng để preview deterministic",
    ],
  },
  {
    id: "special-ability",
    name: "Special Ability",
    nodeLabel: "SpecialAbility",
    module: "special-ability",
    tCode: "SA01",
    route: "/special-abilities",
    purpose: "Master data năng lực đặc thù của character.",
    requiredFields: ["name"],
    optionalFields: ["type", "description", "notes", "tags[]"],
    relations: ["CHARACTER_HAS_SPECIAL_ABILITY <- Character"],
    apis: [
      "GET /special-abilities",
      "POST /special-abilities",
      "PUT /special-abilities/:id",
      "DELETE /special-abilities/:id",
    ],
    notes: ["type: innate | acquired"],
  },
  {
    id: "entity-schema",
    name: "Entity Schema",
    nodeLabel: "EntitySchema",
    module: "schema",
    tCode: "SM01",
    route: "/schemas",
    purpose: "Định nghĩa schema động để mở rộng field theo entity.",
    requiredFields: ["entity", "fields[]"],
    optionalFields: ["id", "title"],
    relations: ["Không phải quan hệ lore, dùng cho dynamic form"],
    apis: ["GET /schemas/:entity", "PUT /schemas/:entity"],
    notes: ["field.type hỗ trợ text/number/textarea/select/multiselect/boolean/date"],
  },
  {
    id: "timeline",
    name: "Timeline",
    nodeLabel: "Timeline",
    module: "timeline",
    tCode: "TI01",
    route: "/timelines",
    purpose: "Trục thời gian và giai đoạn của thế giới/cốt truyện.",
    requiredFields: ["name", "durationYears"],
    optionalFields: [
      "code",
      "isOngoing",
      "summary",
      "description",
      "characteristics[]",
      "dominantForces[]",
      "technologyLevel",
      "powerEnvironment",
      "worldState",
      "majorChanges[]",
      "notes",
      "tags[]",
      "previousId",
      "nextId",
    ],
    relations: ["NEXT/PREVIOUS <-> Timeline", "OCCURS_ON <- Event"],
    apis: [
      "GET /timelines",
      "POST /timelines",
      "DELETE /timelines/:id",
      "POST /timelines/link",
      "POST /timelines/unlink",
      "POST /timelines/relink",
    ],
    notes: [
      "Timeline có danh sách riêng và board riêng",
      "Board timeline mặc định đóng, mở bằng nút Board",
      "Board hỗ trợ pan/zoom/fit/reset + minimap",
    ],
  },
  {
    id: "location",
    name: "Location",
    nodeLabel: "Location",
    module: "location",
    tCode: "LO01",
    route: "/locations",
    purpose: "Không gian địa lý nhiều cấp (structure -> world).",
    requiredFields: ["name"],
    optionalFields: [
      "alias[]",
      "type",
      "typeDetail",
      "category",
      "isHabitable",
      "isSecret",
      "terrain",
      "climate",
      "environment",
      "naturalResources[]",
      "powerDensity",
      "dangerLevel",
      "anomalies[]",
      "restrictions[]",
      "historicalSummary",
      "legend",
      "ruinsOrigin",
      "currentStatus",
      "controlledBy",
      "populationNote",
      "notes",
      "tags[]",
    ],
    relations: ["CONTAINS <-> Location", "SCENE_TAKES_PLACE_IN <- Scene", "OCCURS_IN <- Event"],
    apis: [
      "GET /locations",
      "POST /locations",
      "PUT /locations/:id",
      "DELETE /locations/:id",
      "POST /locations/contains",
      "POST /locations/contains/unlink",
    ],
    notes: ["Quan hệ CONTAINS có sinceYear/untilYear/note"],
  },
  {
    id: "faction",
    name: "Faction",
    nodeLabel: "Faction",
    module: "faction",
    tCode: "FA01",
    route: "/factions",
    purpose: "Tổ chức/phe phái, chính trị, quân sự, ảnh hưởng.",
    requiredFields: ["name"],
    optionalFields: [
      "alias[]",
      "type",
      "alignment",
      "isPublic",
      "isCanon",
      "ideology",
      "goal",
      "doctrine",
      "taboos[]",
      "powerLevel",
      "influenceScope",
      "militaryPower",
      "specialAssets[]",
      "leadershipType",
      "leaderTitle",
      "hierarchyNote",
      "memberPolicy",
      "foundingStory",
      "ageEstimate",
      "majorConflicts[]",
      "reputation",
      "currentStatus",
      "currentStrategy",
      "knownEnemies[]",
      "knownAllies[]",
      "notes",
      "tags[]",
    ],
    relations: ["PARTICIPATES_IN -> Event", "OWNS_ITEM -> Item"],
    apis: [
      "GET /factions",
      "POST /factions",
      "PUT /factions/:id",
      "DELETE /factions/:id",
    ],
    notes: ["Có thể mở rộng quan hệ với location/timeline khi cần"],
  },
  {
    id: "event",
    name: "Event",
    nodeLabel: "Event",
    module: "event",
    tCode: "EV01",
    route: "/events",
    purpose: "Sự kiện narrative/world state với thời điểm, nơi chốn, người tham gia.",
    requiredFields: ["name"],
    optionalFields: [
      "type",
      "typeDetail",
      "scope",
      "locationId",
      "timelineId",
      "timelineYear",
      "timelineMonth",
      "timelineDay",
      "durationValue",
      "durationUnit",
      "startYear",
      "endYear",
      "summary",
      "description",
      "participants[]",
      "notes",
      "tags[]",
    ],
    relations: [
      "OCCURS_IN -> Location",
      "OCCURS_ON -> Timeline",
      "PARTICIPATES_IN <- Character/Faction",
      "ITEM_APPEARS_IN <- Item",
      "SCENE_REFERENCES_EVENT <- Scene",
    ],
    apis: ["GET /events", "POST /events", "PUT /events/:id", "DELETE /events/:id"],
    notes: ["participants chứa role, participationType, outcome, statusChange"],
  },
  {
    id: "arc",
    name: "Arc",
    nodeLabel: "Arc",
    module: "arc",
    tCode: "AR01",
    route: "/arcs",
    purpose: "Mạch truyện cấp cao, chứa chapter.",
    requiredFields: ["name"],
    optionalFields: ["order", "summary", "notes", "tags[]"],
    relations: ["ARC_HAS_CHAPTER -> Chapter"],
    apis: [
      "GET /arcs",
      "POST /arcs",
      "PUT /arcs/:id",
      "DELETE /arcs/:id",
      "GET /arcs/structure",
    ],
    notes: ["Arc structure endpoint trả cây arc/chapter/scene"],
  },
  {
    id: "chapter",
    name: "Chapter",
    nodeLabel: "Chapter",
    module: "chapter",
    tCode: "CP01",
    route: "/chapters",
    purpose: "Đơn vị chương nằm trong arc.",
    requiredFields: ["name"],
    optionalFields: ["order", "summary", "notes", "tags[]", "arcId"],
    relations: ["ARC_HAS_CHAPTER <- Arc", "CHAPTER_HAS_SCENE -> Scene"],
    apis: [
      "GET /chapters",
      "POST /chapters",
      "PUT /chapters/:id",
      "DELETE /chapters/:id",
    ],
    notes: ["arcId dùng cho filter và mapping trong cấu trúc"],
  },
  {
    id: "scene",
    name: "Scene",
    nodeLabel: "Scene",
    module: "scene",
    tCode: "SC01",
    route: "/scenes",
    purpose: "Cảnh cụ thể trong chapter, tham chiếu event/location/character.",
    requiredFields: ["name"],
    optionalFields: [
      "order",
      "summary",
      "content",
      "notes",
      "tags[]",
      "chapterId",
      "eventId",
      "locationId",
      "characterIds[]",
    ],
    relations: [
      "CHAPTER_HAS_SCENE <- Chapter",
      "SCENE_REFERENCES_EVENT -> Event",
      "SCENE_TAKES_PLACE_IN -> Location",
      "SCENE_FEATURES_CHARACTER -> Character",
    ],
    apis: [
      "GET /scenes",
      "POST /scenes",
      "PUT /scenes/:id",
      "DELETE /scenes/:id",
      "POST /scenes/:id/event",
      "DELETE /scenes/:id/event",
      "POST /scenes/:id/location",
      "DELETE /scenes/:id/location",
      "POST /scenes/:id/characters",
    ],
    notes: ["Có cả endpoint put toàn phần và endpoint link chuyên biệt"],
  },
  {
    id: "item",
    name: "Item",
    nodeLabel: "Item",
    module: "item",
    tCode: "IT01",
    route: "/items",
    purpose: "Vật phẩm với trạng thái sở hữu và sức mạnh.",
    requiredFields: ["name"],
    optionalFields: [
      "origin",
      "ownerId",
      "ownerType",
      "status",
      "powerLevel",
      "powerDescription",
      "notes",
      "tags[]",
    ],
    relations: ["OWNS_ITEM <- Character/Faction", "ITEM_APPEARS_IN -> Event"],
    apis: [
      "GET /items",
      "POST /items",
      "PUT /items/:id",
      "DELETE /items/:id",
      "POST /items/:id/event",
      "DELETE /items/:id/event",
      "GET /events/:id/items",
      "GET /items/:id/events",
    ],
    notes: ["status: owned | lost | destroyed"],
  },
  {
    id: "relationship",
    name: "Relationship",
    nodeLabel: "CharacterRelation",
    module: "relationship",
    tCode: "RL01",
    route: "/relationships",
    purpose: "Quan hệ giữa hai nhân vật theo type động của project.",
    requiredFields: ["fromId", "toId", "type"],
    optionalFields: ["startYear", "endYear", "note"],
    relations: ["CHARACTER_RELATES_TO -> Character", "type tham chiếu RelationshipType.code"],
    apis: [
      "GET /character-relations",
      "POST /character-relations",
      "PUT /character-relations",
      "DELETE /character-relations",
    ],
    notes: [
      "Graph view hỗ trợ pan/zoom/fit/reset + minimap",
      "Hỗ trợ kéo-thả node và gom cạnh trùng cặp nhân vật",
      "Danh sách relationship tách riêng với board graph",
      "Board graph mặc định đóng, mở bằng nút Board",
    ],
  },
  {
    id: "relationship-type",
    name: "Relationship Type",
    nodeLabel: "RelationshipType",
    module: "relationship-type",
    tCode: "RT01",
    route: "/relationship-types",
    purpose: "Danh mục loại quan hệ tùy biến cho CharacterRelation.",
    requiredFields: ["code", "name"],
    optionalFields: ["description", "isDirectional", "color", "isActive"],
    relations: ["Được CharacterRelation.type tham chiếu qua code"],
    apis: [
      "GET /relationship-types",
      "POST /relationship-types",
      "PUT /relationship-types/:id",
      "DELETE /relationship-types/:id",
    ],
    notes: [
      "Delete hỗ trợ force khi type đang được dùng bởi character-relations",
      "Code được chuẩn hóa lower-case",
      "Không còn system type cố định, người dùng toàn quyền tạo/sửa/xóa type",
    ],
  },
  {
    id: "conflict-report",
    name: "Conflict Report",
    nodeLabel: "ConflictReport",
    module: "conflict",
    tCode: "CF01",
    route: "/conflicts",
    purpose: "Báo cáo kiểm tra mâu thuẫn dữ liệu/lore toàn project (read-only).",
    requiredFields: ["Không có input bắt buộc"],
    optionalFields: ["scope filter (tuỳ phiên bản)", "rule sets (tuỳ mở rộng)"],
    relations: [
      "Không phải node graph độc lập",
      "Tổng hợp từ Character/Timeline/Event/Scene/Location/Rule",
    ],
    apis: ["GET /conflicts"],
    notes: [
      "UI hiện tại dùng để tra cứu và debug consistency",
      "Kết quả phụ thuộc dữ liệu hiện có trong project database",
    ],
  },
  {
    id: "world-rule",
    name: "World Rule",
    nodeLabel: "WorldRule",
    module: "worldrule",
    tCode: "WR01",
    route: "/world-rules",
    purpose: "Luật vận hành thế giới, ràng buộc và ngoại lệ.",
    requiredFields: ["title"],
    optionalFields: [
      "category",
      "description",
      "scope",
      "constraints",
      "exceptions",
      "status",
      "version",
      "validFrom",
      "validTo",
      "notes",
      "tags[]",
    ],
    relations: ["Hiện chưa mở quan hệ graph bắt buộc"],
    apis: [
      "GET /world-rules",
      "POST /world-rules",
      "PUT /world-rules/:id",
      "DELETE /world-rules/:id",
    ],
    notes: ["status: draft | active | deprecated"],
  },
];

export const nodeDocById = new Map(nodeDocs.map((node) => [node.id, node]));
