export const endpoints = {
  health: "/health",
  overview: "/overview",
  projects: "/projects",
  characters: "/characters",
  timelines: "/timelines",
  timelineLink: "/timelines/link",
  timelineUnlink: "/timelines/unlink",
  timelineRelink: "/timelines/relink",
  locations: "/locations",
  factions: "/factions",
  events: "/events",
  arcs: "/arcs",
  arcStructure: "/arcs/structure",
  chapters: "/chapters",
  scenes: "/scenes",
  items: "/items",
  characterRelations: "/character-relations",
  conflicts: "/conflicts",
  worldRules: "/world-rules",
};
