export const nodeLabels = {
  project: "Project",
  overview: "Overview",
  character: "Character",
  race: "Race",
  rank: "Rank",
  specialAbility: "SpecialAbility",
  event: "Event",
  faction: "Faction",
  timeline: "Timeline",
  location: "Location",
  arc: "Arc",
  chapter: "Chapter",
  scene: "Scene",
  item: "Item",
  worldRule: "WorldRule",
};
