export const relationTypes = {
  participatesIn: "PARTICIPATES_IN",
  alliedWith: "ALLIED_WITH",
  occursIn: "OCCURS_IN",
  occursOn: "OCCURS_ON",
  timelineNext: "NEXT",
  timelinePrevious: "PREVIOUS",
  contains: "CONTAINS",
  arcHasChapter: "ARC_HAS_CHAPTER",
  chapterHasScene: "CHAPTER_HAS_SCENE",
  sceneReferencesEvent: "SCENE_REFERENCES_EVENT",
  sceneFeaturesCharacter: "SCENE_FEATURES_CHARACTER",
  sceneTakesPlaceIn: "SCENE_TAKES_PLACE_IN",
  ownsItem: "OWNS_ITEM",
  itemAppearsIn: "ITEM_APPEARS_IN",
  characterRelatesTo: "CHARACTER_RELATES_TO",
  characterHasRace: "CHARACTER_HAS_RACE",
};
