export const relationTypes = {
  participatesIn: "PARTICIPATES_IN",
  alliedWith: "ALLIED_WITH",
  occursIn: "OCCURS_IN",
  occursOn: "OCCURS_ON",
  timelineNext: "NEXT",
  timelinePrevious: "PREVIOUS",
  rankNext: "RANK_NEXT",
  hasRank: "HAS_RANK",
  contains: "CONTAINS",
  arcHasChapter: "ARC_HAS_CHAPTER",
  chapterHasScene: "CHAPTER_HAS_SCENE",
  sceneReferencesEvent: "SCENE_REFERENCES_EVENT",
  sceneFeaturesCharacter: "SCENE_FEATURES_CHARACTER",
  sceneTakesPlaceIn: "SCENE_TAKES_PLACE_IN",
  ownsItem: "OWNS_ITEM",
  itemAppearsIn: "ITEM_APPEARS_IN",
  characterRelatesTo: "CHARACTER_RELATES_TO",
  characterHasRace: "CHARACTER_HAS_RACE",
  characterHasRank: "CHARACTER_HAS_RANK",
  characterHasSpecialAbility: "CHARACTER_HAS_SPECIAL_ABILITY",
  usesEnergy: "USES_ENERGY",
  hasEnergyTier: "HAS_ENERGY_TIER",
  energyNext: "ENERGY_NEXT",
  energyConvertsTo: "ENERGY_CONVERTS_TO",
};
