import { RouteConfig } from "../../routes";
import { locationController } from "./location.controller";

export const locationRoutes: RouteConfig[] = [
  {
    method: "POST",
    path: "/locations",
    handler: locationController.createLocation,
    schema: {
      tags: ["Location"],
      summary: "Create location",
      body: {
        type: "object",
        required: ["id", "name"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          type: { type: "string" },
          category: { type: "string" },
          isHabitable: { type: "boolean" },
          isSecret: { type: "boolean" },
          terrain: { type: "string" },
          climate: { type: "string" },
          environment: { type: "string" },
          naturalResources: { type: "array", items: { type: "string" } },
          powerDensity: { type: "string" },
          dangerLevel: { type: "number" },
          anomalies: { type: "array", items: { type: "string" } },
          restrictions: { type: "array", items: { type: "string" } },
          historicalSummary: { type: "string" },
          legend: { type: "string" },
          ruinsOrigin: { type: "string" },
          currentStatus: { type: "string" },
          controlledBy: { type: "string" },
          populationNote: { type: "string" },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        201: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                type: { type: "string" },
                category: { type: "string" },
                isHabitable: { type: "boolean" },
                isSecret: { type: "boolean" },
                terrain: { type: "string" },
                climate: { type: "string" },
                environment: { type: "string" },
                naturalResources: { type: "array", items: { type: "string" } },
                powerDensity: { type: "string" },
                dangerLevel: { type: "number" },
                anomalies: { type: "array", items: { type: "string" } },
                restrictions: { type: "array", items: { type: "string" } },
                historicalSummary: { type: "string" },
                legend: { type: "string" },
                ruinsOrigin: { type: "string" },
                currentStatus: { type: "string" },
                controlledBy: { type: "string" },
                populationNote: { type: "string" },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
];
