import { RouteConfig } from "../../routes";
import { locationController } from "./location.controller";

export const locationRoutes: RouteConfig[] = [
  {
    method: "GET",
    path: "/locations",
    handler: locationController.getAllLocations,
    schema: {
      tags: ["Location"],
      summary: "Get all locations",
      querystring: {
        type: "object",
        properties: {
          q: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
          name: { type: "string" },
          tag: { type: "string" },
          type: { type: "string" },
          category: { type: "string" },
          isSecret: { type: "boolean" },
          isHabitable: { type: "boolean" },
          parentId: { type: "string" },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            data: {
              type: "array",
              items: { type: "object", additionalProperties: true },
            },
            meta: {
              type: "object",
              properties: {
                q: { type: "string" },
                limit: { type: "number" },
                offset: { type: "number" },
                name: { type: "string" },
                tag: { type: "string" },
                type: { type: "string" },
                category: { type: "string" },
                isSecret: { type: "boolean" },
                isHabitable: { type: "boolean" },
                parentId: { type: "string" },
                total: { type: "number" },
              },
            },
          },
        },
      },
    },
  },
  {
    method: "POST",
    path: "/locations",
    handler: locationController.createLocation,
    schema: {
      tags: ["Location"],
      summary: "Create location",
      body: {
        type: "object",
        required: ["name", "type"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          description: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          type: { type: "string" },
          typeDetail: { type: "string" },
          category: { type: "string" },
          isHabitable: { type: "boolean" },
          isSecret: { type: "boolean" },
          terrain: { type: "string" },
          climate: { type: "string" },
          environment: { type: "string" },
          naturalResources: { type: "array", items: { type: "string" } },
          powerDensity: { type: "string" },
          dangerLevel: { type: "number" },
          anomalies: { type: "array", items: { type: "string" } },
          restrictions: { type: "array", items: { type: "string" } },
          historicalSummary: { type: "string" },
          legend: { type: "string" },
          ruinsOrigin: { type: "string" },
          currentStatus: { type: "string" },
          controlledBy: { type: "string" },
          populationNote: { type: "string" },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        201: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                description: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                type: { type: "string" },
                typeDetail: { type: "string" },
                category: { type: "string" },
                isHabitable: { type: "boolean" },
                isSecret: { type: "boolean" },
                terrain: { type: "string" },
                climate: { type: "string" },
                environment: { type: "string" },
                naturalResources: { type: "array", items: { type: "string" } },
                powerDensity: { type: "string" },
                dangerLevel: { type: "number" },
                anomalies: { type: "array", items: { type: "string" } },
                restrictions: { type: "array", items: { type: "string" } },
                historicalSummary: { type: "string" },
                legend: { type: "string" },
                ruinsOrigin: { type: "string" },
                currentStatus: { type: "string" },
                controlledBy: { type: "string" },
                populationNote: { type: "string" },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
  {
    method: "PUT",
    path: "/locations/:id",
    handler: locationController.updateLocation,
    schema: {
      tags: ["Location"],
      summary: "Update location",
      body: {
        type: "object",
        required: ["name", "type"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          description: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          type: { type: "string" },
          typeDetail: { type: "string" },
          category: { type: "string" },
          isHabitable: { type: "boolean" },
          isSecret: { type: "boolean" },
          terrain: { type: "string" },
          climate: { type: "string" },
          environment: { type: "string" },
          naturalResources: { type: "array", items: { type: "string" } },
          powerDensity: { type: "string" },
          dangerLevel: { type: "number" },
          anomalies: { type: "array", items: { type: "string" } },
          restrictions: { type: "array", items: { type: "string" } },
          historicalSummary: { type: "string" },
          legend: { type: "string" },
          ruinsOrigin: { type: "string" },
          currentStatus: { type: "string" },
          controlledBy: { type: "string" },
          populationNote: { type: "string" },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                description: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                type: { type: "string" },
                typeDetail: { type: "string" },
                category: { type: "string" },
                isHabitable: { type: "boolean" },
                isSecret: { type: "boolean" },
                terrain: { type: "string" },
                climate: { type: "string" },
                environment: { type: "string" },
                naturalResources: { type: "array", items: { type: "string" } },
                powerDensity: { type: "string" },
                dangerLevel: { type: "number" },
                anomalies: { type: "array", items: { type: "string" } },
                restrictions: { type: "array", items: { type: "string" } },
                historicalSummary: { type: "string" },
                legend: { type: "string" },
                ruinsOrigin: { type: "string" },
                currentStatus: { type: "string" },
                controlledBy: { type: "string" },
                populationNote: { type: "string" },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        404: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
  {
    method: "DELETE",
    path: "/locations/:id",
    handler: locationController.deleteLocation,
    schema: {
      tags: ["Location"],
      summary: "Delete location",
      response: {
        204: { type: "null" },
        404: { type: "object", properties: { message: { type: "string" } } },
      },
    },
  },
  {
    method: "POST",
    path: "/locations/contains",
    handler: locationController.createContains,
    schema: {
      tags: ["Location"],
      summary: "Link locations with CONTAINS",
      body: {
        type: "object",
        required: ["parentId", "childId"],
        properties: {
          parentId: { type: "string" },
          childId: { type: "string" },
          sinceYear: { type: ["number", "null"] },
          untilYear: { type: ["number", "null"] },
          note: { type: ["string", "null"] },
        },
      },
      response: {
        200: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        404: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        409: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
  {
    method: "POST",
    path: "/locations/contains/unlink",
    handler: locationController.deleteContains,
    schema: {
      tags: ["Location"],
      summary: "Unlink locations CONTAINS",
      body: {
        type: "object",
        required: ["childId"],
        properties: {
          parentId: { type: "string" },
          childId: { type: "string" },
        },
      },
      response: {
        200: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
];
