import { RouteConfig } from "../../routes";
import { factionController } from "./faction.controller";

export const factionRoutes: RouteConfig[] = [
  {
    method: "GET",
    path: "/factions",
    handler: factionController.getAllFactions,
    schema: {
      tags: ["Faction"],
      summary: "Get all factions",
      response: {
        200: {
          type: "object",
          properties: {
            data: {
              type: "array",
              items: { type: "object", additionalProperties: true },
            },
          },
        },
      },
    },
  },
  {
    method: "POST",
    path: "/factions",
    handler: factionController.createFaction,
    schema: {
      tags: ["Faction"],
      summary: "Create faction",
      body: {
        type: "object",
        required: ["name"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          type: { type: "string" },
          alignment: { type: "string" },
          isPublic: { type: "boolean" },
          isCanon: { type: "boolean" },
          ideology: { type: "string" },
          goal: { type: "string" },
          doctrine: { type: "string" },
          taboos: { type: "array", items: { type: "string" } },
          powerLevel: { type: "number" },
          influenceScope: { type: "string" },
          militaryPower: { type: "string" },
          specialAssets: { type: "array", items: { type: "string" } },
          leadershipType: { type: "string" },
          leaderTitle: { type: "string" },
          hierarchyNote: { type: "string" },
          memberPolicy: { type: "string" },
          foundingStory: { type: "string" },
          ageEstimate: { type: "string" },
          majorConflicts: { type: "array", items: { type: "string" } },
          reputation: { type: "string" },
          currentStatus: { type: "string" },
          currentStrategy: { type: "string" },
          knownEnemies: { type: "array", items: { type: "string" } },
          knownAllies: { type: "array", items: { type: "string" } },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        201: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                type: { type: "string" },
                alignment: { type: "string" },
                isPublic: { type: "boolean" },
                isCanon: { type: "boolean" },
                ideology: { type: "string" },
                goal: { type: "string" },
                doctrine: { type: "string" },
                taboos: { type: "array", items: { type: "string" } },
                powerLevel: { type: "number" },
                influenceScope: { type: "string" },
                militaryPower: { type: "string" },
                specialAssets: { type: "array", items: { type: "string" } },
                leadershipType: { type: "string" },
                leaderTitle: { type: "string" },
                hierarchyNote: { type: "string" },
                memberPolicy: { type: "string" },
                foundingStory: { type: "string" },
                ageEstimate: { type: "string" },
                majorConflicts: { type: "array", items: { type: "string" } },
                reputation: { type: "string" },
                currentStatus: { type: "string" },
                currentStrategy: { type: "string" },
                knownEnemies: { type: "array", items: { type: "string" } },
                knownAllies: { type: "array", items: { type: "string" } },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
  {
    method: "PUT",
    path: "/factions/:id",
    handler: factionController.updateFaction,
    schema: {
      tags: ["Faction"],
      summary: "Update faction",
      body: {
        type: "object",
        required: ["name"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          type: { type: "string" },
          alignment: { type: "string" },
          isPublic: { type: "boolean" },
          isCanon: { type: "boolean" },
          ideology: { type: "string" },
          goal: { type: "string" },
          doctrine: { type: "string" },
          taboos: { type: "array", items: { type: "string" } },
          powerLevel: { type: "number" },
          influenceScope: { type: "string" },
          militaryPower: { type: "string" },
          specialAssets: { type: "array", items: { type: "string" } },
          leadershipType: { type: "string" },
          leaderTitle: { type: "string" },
          hierarchyNote: { type: "string" },
          memberPolicy: { type: "string" },
          foundingStory: { type: "string" },
          ageEstimate: { type: "string" },
          majorConflicts: { type: "array", items: { type: "string" } },
          reputation: { type: "string" },
          currentStatus: { type: "string" },
          currentStrategy: { type: "string" },
          knownEnemies: { type: "array", items: { type: "string" } },
          knownAllies: { type: "array", items: { type: "string" } },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                type: { type: "string" },
                alignment: { type: "string" },
                isPublic: { type: "boolean" },
                isCanon: { type: "boolean" },
                ideology: { type: "string" },
                goal: { type: "string" },
                doctrine: { type: "string" },
                taboos: { type: "array", items: { type: "string" } },
                powerLevel: { type: "number" },
                influenceScope: { type: "string" },
                militaryPower: { type: "string" },
                specialAssets: { type: "array", items: { type: "string" } },
                leadershipType: { type: "string" },
                leaderTitle: { type: "string" },
                hierarchyNote: { type: "string" },
                memberPolicy: { type: "string" },
                foundingStory: { type: "string" },
                ageEstimate: { type: "string" },
                majorConflicts: { type: "array", items: { type: "string" } },
                reputation: { type: "string" },
                currentStatus: { type: "string" },
                currentStrategy: { type: "string" },
                knownEnemies: { type: "array", items: { type: "string" } },
                knownAllies: { type: "array", items: { type: "string" } },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: { message: { type: "string" } },
        },
        404: {
          type: "object",
          properties: { message: { type: "string" } },
        },
      },
    },
  },
  {
    method: "DELETE",
    path: "/factions/:id",
    handler: factionController.deleteFaction,
    schema: {
      tags: ["Faction"],
      summary: "Delete faction",
      response: {
        204: { type: "null" },
        404: { type: "object", properties: { message: { type: "string" } } },
      },
    },
  },
];
