import { RouteConfig } from "../../routes";
import { characterController } from "./character.controller";

export const characterRoutes: RouteConfig[] = [
  {
    method: "GET",
    path: "/characters",
    handler: characterController.getAllCharacters,
    schema: {
      tags: ["Character"],
      summary: "Get all characters",
      querystring: {
        type: "object",
        properties: {
          q: { type: "string" },
          limit: { type: "number" },
          offset: { type: "number" },
          name: { type: "string" },
          tag: { type: "string" },
          race: { type: "string" },
          specialAbility: { type: "string" },
          gender: { type: "string", enum: ["male", "female", "other"] },
          status: { type: "string", enum: ["Alive", "Dead"] },
          level: { type: "string" },
          isMainCharacter: { type: "boolean" },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            data: {
              type: "array",
              items: { type: "object", additionalProperties: true },
            },
            meta: {
              type: "object",
              properties: {
                q: { type: "string" },
                limit: { type: "number" },
                offset: { type: "number" },
                name: { type: "string" },
                tag: { type: "string" },
                race: { type: "string" },
                specialAbility: { type: "string" },
                gender: { type: "string" },
                status: { type: "string" },
                level: { type: "string" },
                isMainCharacter: { type: "boolean" },
              },
            },
          },
        },
      },
    },
  },
  {
    method: "POST",
    path: "/characters",
    handler: characterController.createCharacter,
    schema: {
      tags: ["Character"],
      summary: "Create character",
      body: {
        type: "object",
        required: ["name", "gender", "age"],
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          level: { type: "string" },
          status: { type: "string", enum: ["Alive", "Dead"] },
          isMainCharacter: { type: "boolean" },
          gender: { type: "string", enum: ["male", "female", "other"] },
          age: { type: "number" },
          race: { type: "string" },
          specialAbilities: { type: "array", items: { type: "string" } },
          extra: { type: "object", additionalProperties: true },
          appearance: { type: "string" },
          height: { type: "number" },
          distinctiveTraits: { type: "array", items: { type: "string" } },
          personalityTraits: { type: "array", items: { type: "string" } },
          beliefs: { type: "array", items: { type: "string" } },
          fears: { type: "array", items: { type: "string" } },
          desires: { type: "array", items: { type: "string" } },
          weaknesses: { type: "array", items: { type: "string" } },
          origin: { type: "string" },
          background: { type: "string" },
          trauma: { type: "array", items: { type: "string" } },
          secret: { type: "string" },
          currentLocation: { type: "string" },
          currentGoal: { type: "string" },
          currentAffiliation: { type: "string" },
          powerState: { type: "string" },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        201: {
          type: "object",
          properties: {
            data: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                alias: { type: "array", items: { type: "string" } },
                level: { type: "string" },
                status: { type: "string", enum: ["Alive", "Dead"] },
                isMainCharacter: { type: "boolean" },
                gender: { type: "string", enum: ["male", "female", "other"] },
                age: { type: "number" },
                race: { type: "string" },
                specialAbilities: { type: "array", items: { type: "string" } },
                extra: { type: "object", additionalProperties: true },
                appearance: { type: "string" },
                height: { type: "number" },
                distinctiveTraits: { type: "array", items: { type: "string" } },
                personalityTraits: { type: "array", items: { type: "string" } },
                beliefs: { type: "array", items: { type: "string" } },
                fears: { type: "array", items: { type: "string" } },
                desires: { type: "array", items: { type: "string" } },
                weaknesses: { type: "array", items: { type: "string" } },
                origin: { type: "string" },
                background: { type: "string" },
                trauma: { type: "array", items: { type: "string" } },
                secret: { type: "string" },
                currentLocation: { type: "string" },
                currentGoal: { type: "string" },
                currentAffiliation: { type: "string" },
                powerState: { type: "string" },
                notes: { type: "string" },
                tags: { type: "array", items: { type: "string" } },
                createdAt: { type: "string", format: "date-time" },
                updatedAt: { type: "string", format: "date-time" },
              },
            },
          },
        },
        400: {
          type: "object",
          properties: {
            message: { type: "string" },
          },
        },
      },
    },
  },
  {
    method: "PUT",
    path: "/characters/:id",
    handler: characterController.updateCharacter,
    schema: {
      tags: ["Character"],
      summary: "Update character",
      body: {
        type: "object",
        required: ["name", "gender", "age"],
        properties: {
          name: { type: "string" },
          alias: { type: "array", items: { type: "string" } },
          level: { type: "string" },
          status: { type: "string", enum: ["Alive", "Dead"] },
          isMainCharacter: { type: "boolean" },
          gender: { type: "string", enum: ["male", "female", "other"] },
          age: { type: "number" },
          race: { type: "string" },
          specialAbilities: { type: "array", items: { type: "string" } },
          extra: { type: "object", additionalProperties: true },
          appearance: { type: "string" },
          height: { type: "number" },
          distinctiveTraits: { type: "array", items: { type: "string" } },
          personalityTraits: { type: "array", items: { type: "string" } },
          beliefs: { type: "array", items: { type: "string" } },
          fears: { type: "array", items: { type: "string" } },
          desires: { type: "array", items: { type: "string" } },
          weaknesses: { type: "array", items: { type: "string" } },
          origin: { type: "string" },
          background: { type: "string" },
          trauma: { type: "array", items: { type: "string" } },
          secret: { type: "string" },
          currentLocation: { type: "string" },
          currentGoal: { type: "string" },
          currentAffiliation: { type: "string" },
          powerState: { type: "string" },
          notes: { type: "string" },
          tags: { type: "array", items: { type: "string" } },
        },
      },
      response: {
        200: {
          type: "object",
          properties: {
            data: { type: "object", additionalProperties: true },
          },
        },
        400: { type: "object", properties: { message: { type: "string" } } },
        404: { type: "object", properties: { message: { type: "string" } } },
      },
    },
  },
  {
    method: "DELETE",
    path: "/characters/:id",
    handler: characterController.deleteCharacter,
    schema: {
      tags: ["Character"],
      summary: "Delete character",
      response: {
        204: { type: "null" },
        404: { type: "object", properties: { message: { type: "string" } } },
      },
    },
  },
];
